[workspace]
members = [".", "crates/sqlite-es"]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "deny"
enum_glob_use = "deny"

# `priority = -1` allow for allowing lints enabled by a group to be re-disabled
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }

doc_markdown = "allow"
items_after_statements = "allow"
redundant_pub_crate = "allow"

[workspace.dependencies]
async-trait = "0.1.89"
cqrs-es = "0.4.12"
rocket = "0.5.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = [
  "sqlite",
  "chrono",
  "runtime-tokio-rustls",
] }
thiserror = "2.0.17"
tracing = "0.1.41"

[package]
name = "st0x-issuance"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket.workspace = true
sqlx.workspace = true
tracing.workspace = true
sqlite-es = { path = "crates/sqlite-es" }

[lints]
workspace = true
