services:
  issuance-bot:
    image: ${DOCKER_IMAGE}
    pull_policy: ${PULL_POLICY}
    container_name: issuance-bot
    command: ["./server"]
    environment:
      - DATABASE_URL=sqlite:///data/issuance.db
      - FIREBLOCKS_SECRET_PATH=/data/fireblocks_secret.issuance.key
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ${DATA_VOLUME_PATH}:/data
    restart: unless-stopped
